### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [goddessofcats/prj-rev-bwfs-dasmoto#6]
https://github.com/goddessofcats/prj-rev-bwfs-dasmoto/blob/master/dasmoto/css/style.css#L2-L9

This code can (and should) be simplified. 

If all of the elements on the page should have the same font-family, then use the universal selector `*`.

```css
* {
  font-family: Helvetica;
}
```

Or just list out the general elements that need that style:

```css
h1, h2, p, span {
  font-family: Helvetica;
}
```
